### ISSUE TITLE
PyQt5 direct imports

### ISSUE THREAD

**Issue by jaimergp** [aics-int/napari-allencell-annotator#16]
Hi team!

I see that this project recently added an explicit dependency on PyQt5, while also relying on `qtpy`. Is there a reason to bypass the `qtpy` wrappers? They should be compatible and, if we stick to `qtpy`, PySide2 compatibility is given for free.

But maybe I am missing a technical detail.

(This is important for the conda-forge packaging aspects, where we prefer to remain binding-agnostic so people can choose pyqt or pyside, plugins included).

**Comment by bbridge0200** [comment]
Will change to qtpy! Thanks :)
