### ISSUE TITLE
Skipped images with no annotation not saved to csv 

### ISSUE THREAD

**Issue by memeramita** [aics-int/napari-allencell-annotator#61]
Note: Can be recreated only after the file widget is fixed to be able to display images

Step to create:

1. Import 4 images
2. Create a template
3. Start annotating
4. Annotate the first image
5. Use file widget to skip to and annotate the third image
6. Click next
7. Annotate the last image
8. Click exit
9. The csv file does not contain the second image

Error:
The csv file should contain all 4 images.

**Comment by yrkim98** [comment]
duplicate/side effect of https://github.com/aics-int/napari-allencell-annotator/issues/55
